version: '3'
services:

  nginx:
    image: nginx:alpine
    container_name: deploy
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./deploy:/var/www/html/deploy
      - ./nginx/deploy.conf:/etc/nginx/conf.d/default.conf